# Generated by Django 4.1.1 on 2023-05-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0034_remove_memory_random_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='antonym',
            field=models.ManyToManyField(blank=True, to='exams.word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='related',
            field=models.ManyToManyField(blank=True, to='exams.word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='synonym',
            field=models.ManyToManyField(blank=True, to='exams.word'),
        ),
    ]
