# Generated by Django 2.1.7 on 2022-09-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiss', '0012_league_win_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='ranking_criteria',
            field=models.CharField(default='', max_length=32),
        ),
    ]
