# Generated by Django 4.1.1 on 2023-05-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiss', '0013_league_ranking_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='tournament_stage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='tournament_stage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='round',
            name='tournament_stage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='family',
            field=models.ManyToManyField(blank=True, to='swiss.player'),
        ),
    ]
