# Generated by Django 4.1.1 on 2023-05-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swiss', '0014_league_tournament_stage_player_tournament_stage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='tournament_stage',
        ),
        migrations.RemoveField(
            model_name='player',
            name='tournament_stage',
        ),
    ]
